before_install:
  - sudo apt update
  - sudo apt install libpocl2 libpocl-dev pocl-opencl-icd
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
