language: rust
dist: bionic
before_install:
  - sudo apt update
  - sudo apt install pocl-opencl-icd
os:
  - linux
apt:
  packages:
    - pocl-opencl-icd
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
