before_install:
  - sudo apt update
  - sudo apt install beignet-opencl-icd opencl-headers
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
